export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const FILMS_REPOSITORY = 'FILMS_REPOSITORY';
export const FILMS_GENRIC_REPOSITORY = 'FILMS_GENRIC_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const USERSETTING_REPOSITORY = 'USERSETTING_REPOSITORY';
export const FILM_COMMENTS_REPOSITORY = 'FILM_COMMENTS_REPOSITORY';
